### Importing the required libraries, packages and modules

In [74]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report,confusion_matrix

In [75]:
#Reading the data from the required file
data= pd.read_csv("Iris.csv")
#Printing out the first five rows
data.head(n=5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Replacing the Species column with numbers.

In [76]:
#Listing out the unique values in the "Species" column.
m= list(data["Species"].unique())
print(m)

['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']


In [77]:
#Replacing the unique values by numbers
data.Species.replace({"Iris-setosa":0,"Iris-versicolor":1,"Iris-virginica":2}, inplace=True)
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [78]:
#Assigning x and y values to the required column values.
x= data.iloc[:, 3:5]
y= data.iloc[:, 5]


### Training the model.

In [61]:
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.3, random_state=0)

In [79]:
#Aplying SVM classification to the dataset.
svclassifier= SVC(kernel="linear")
svclassifier.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [80]:
#Making predictions 
y_pred= svclassifier.predict(x_test)

### Evaluating the model

In [84]:
cm= confusion_matrix(y_test, y_pred)
cr= classification_report(y_test, y_pred)
print(cm)
print(cr)

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [82]:
#accuracy
print("The Accuracy of support vector machine on test data is {}".format(svclassifier.score(x_test, y_test)))

The Accuracy of support vector machine on test data is 0.9777777777777777
